services:
  code-server:
    image: dangtong76/cicd-devops-ide:amd64
    
    # Telepresence 권한
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    container_name: ide
    networks:
      - kind
    environment:
      AUTH: none
    env_file:
      - .env
    working_dir: /code
    ports:
      - "8080:8080"
      - "8444:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - devops-cicd-apps:/code/devops-cicd-apps
      - devops-cicd-vscode:/config

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    networks:
      - kind
    privileged: true
    environment:
      - SHARED_DIRECTORY=/exports
      # 아래는 실습용(접근 쉬움). 운영에선 제한 필요
      - PERMITTED="172.21.0.0/16"
    volumes:
      - nfs-server-volume:/exports
    # NFS 포트 (같은 docker 네트워크면 없어도 되지만, 디버깅용으로 열어두면 편함)
    ports:
      - "2049:2049"
      - "11111:111"
      - "20048:20048"
    restart: unless-stopped


networks:
  kind:
    name: kind
    external: true

volumes:
  nfs-server-volume:
    external: true
    name: nfs-server-volume
  devops-cicd-apps:
    external: true
    name: devops-cicd-apps
  devops-cicd-vscode:
    external: true
    name: devops-cicd-vscode
  